name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm i -g @antfu/ni

      - name: Create output directory
        run: mkdir -p output

      - name: Build all lecture slides
        run: |
          for dir in lecture*/; do
            if [ -f "$dir/package.json" ]; then
              echo "Building $dir"
              cd $dir
              nci
              nr build --base /${{github.event.repository.name}}/${dir%/}/
              mkdir -p ../output/${dir%/}
              mv dist/* ../output/${dir%/}
              cd ..
            fi
          done

      - name: Convert README.md to index.html
        run: |
          sudo apt-get install -y pandoc
          pandoc README.md -o output/index.html --metadata title="Home"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
